name: Deploy React CSR
on: 
  push:
    branches:
      - main
      - feature/**
      - "!feature/login"
  workflow_dispatch:
  pull_request:
    types:
      - opened
#env:
#  node-version: '22.15.1'
jobs:
  build:
    # environment : Prod
    runs-on: ubuntu-latest
    #container:
      #image: node:22.15.1
      # env:
      #  NODE_ENV: production
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install and Cache
        uses: ./.github/actions/install-cache
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."
  notify-fail:
    runs-on: ubuntu-latest
    needs:
      - build
    if: failure()
    steps:
      - name: Notify to Discord Text Channel
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build Failed :( By Gjee Handsome and cool'
  notify-success:
    runs-on: ubuntu-latest
    needs:
      - build
    if: success()
    steps:
      - name: Notify to Discord Text Channel
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build Success :) By Gjee Handsome and cool'


        
