name: Deploy React CSR
on: 
  # push:
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  lint:
    #npm run lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.1'
      - name: Install depens
        run: npm install
      - name: Run lint
        run: npm run lint

  deploy:
    needs: 
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.1'
      - name: Install depens
        run: npm install
      - name: Build
        run: npm run build
      - name: List dist/
        run: ls dist/
      - name: Deploy
        run: echo "Deploying..."
