name: Deploy to surge
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build React router
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        id: setup-bun
        with:
          bun-version: latest
      - name: Install dependencies
        id: install
        run: bun install
      - name: Build
        id: build
        run: bun run build
      - name: Upload artifacts
        id: upload-dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: |
            dist

  deploy:
    name: Deploy to surge
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: ./dist
      - name: Deploy to surge
        id: deploy
        uses: ./.github/actions/deploy-surge
        with:
          domain: poporing.surge.sh
          token: ${{ secrets.SURGE_TOKEN }}
          email: ${{ vars.SURGE_EMAIL }}
          dist-folder: ./dist